### ISSUE TITLE
PCB Circuit finalised

### ISSUE THREAD

**Issue by yash-chandna** [pixelwave/Remote-PC-Switch#1]
Hey bro. love your project, can you drop a final pcb schematic if possible?

**Comment by pixelwave** [comment]
Hi @yash-chandna I am actually using off the shelve components when it comes to the DP and USB Switches which I disassembled - no custom PCB's.

Some of the hardware used:

- **CHENLENIC Displayport 16K Bi-Direction 2x1** 16K@60Hz 4K@240Hz 2 in 1 Out 1 in 2 Out Switch Converter for Large Screens
- **YIWENTEC USB-C USB 3.1 Type-C 8K Switch Bi-Direction** 8K @ 30Hz 4K @ 120Hz Power Delivery 100W 10Gbps Data Transfer Multifunction Splitter Converter (8K)

Each retails around 20-30$ on amazon but can also be found cheaper at Aliexpress or similar.
